
// REFINED PROXY QUESTIONNAIRE (58 Items)
// Based on "Proxy GPI Questionnaire" derived from Purified Factor Analysis

export const studentGunaItems = [
    // --- SECTION 1: ACADEMIC & WORK LIFE (Deadlines, Success, Failure) ---
    { id: "S12", text: "If you are working on a project that looks like it will fail, do you continue to put in your best effort until the very end?", category: "sattva", domain: "academic" },
    { id: "S6", text: "How much time per week do you spend voluntarily learning something new (reading, watching documentaries) just for the sake of understanding?", category: "sattva", domain: "academic" },
    { id: "R1", text: "If taking a shortcut (like skipping a queue or bending a regulation) would guarantee you a major win, how likely are you to take it?", category: "rajas", domain: "academic" },
    { id: "R3", text: "When solving a problem, how often do you dismiss traditional or old-fashioned approaches in favor of your own logic?", category: "rajas", domain: "academic" },
    { id: "R4", text: "How often do you feel a rush of happiness or pride when you think about the possessions or assets you own?", category: "rajas", domain: "academic" },
    { id: "R7", text: "How often do you feel a surge of elation or excitement when things work out well for you?", category: "rajas", domain: "academic" },
    { id: "T6", text: "How often do you put off important tasks until the last minute, even when you know it will stress you out?", category: "tamas", domain: "academic" },
    { id: "T7", text: "When faced with a complex problem, how often do you freeze up and wait for someone else to solve it for you?", category: "tamas", domain: "academic" },
    { id: "T8", text: "Do you frequently look at your life and feel 'stuck' or like you are 'falling behind' everyone else?", category: "tamas", domain: "academic" },
    { id: "T9", text: "If a gym workout or a study session gets difficult, how likely are you to quit early and tell yourself 'I'll do it tomorrow'?", category: "tamas", domain: "academic" },
    { id: "T12", text: "How many New Year's resolutions or self-improvement plans have you started and dropped within 2 weeks?", category: "tamas", domain: "academic" },
    { id: "T20", text: "How often does your work or studies feel like a major source of anxiety for you?", category: "tamas", domain: "academic" },

    // --- SECTION 2: SOCIAL INTERACTIONS (Friends, Conflict, Status) ---
    { id: "S3", text: "If an elderly family member gives you advice that contradicts your own plans, how likely are you to listen respectfully and seriously consider their perspective?", category: "sattva", domain: "social" },
    { id: "S4", text: "In everyday conversations, how much effort do you make to ensure your words don't irritate or hurt others?", category: "sattva", domain: "social" },
    { id: "S9", text: "If you promise to help a friend move house, but wake up feeling tired and lazy, how likely are you to go anyway simply because you gave your word?", category: "sattva", domain: "social" },
    { id: "S11", text: "How often do you treat the campus janitor/security guard with the exact same respect and patience as you do your Professor or Dean?", category: "sattva", domain: "social" },
    { id: "R2", text: "If a friend invites you to a lecture on philosophy or spirituality, how likely are you to decline because you find it 'boring' or 'useless'?", category: "rajas", domain: "social" },
    { id: "R5", text: "How often do you find yourself admiring or following rich influencers and celebrities rather than scientists or social workers?", category: "rajas", domain: "social" },
    { id: "R13", text: "If someone asks for a donation, do you feel annoyed or resentful, even if you eventually give a small amount?", category: "rajas", domain: "social" },
    { id: "T1", text: "When things go wrong in your life, how often do you feel that it was completely someone else's fault at 'the world is against you'?", category: "tamas", domain: "social" },
    { id: "T4", text: "In your head or with friends, how often do you find yourself making fun of or judging strangers/acquaintances?", category: "tamas", domain: "social" },
    { id: "T11", text: "How many times a week do you feel a flash of rage (at traffic, people, or technology)?", category: "tamas", domain: "social" },
    { id: "T15", text: "Do you feel like you are always the one giving in relationships while others just take from you?", category: "tamas", domain: "social" },
    { id: "T18", text: "When talking to friends, how often do you find yourself mostly complaining about your problems?", category: "tamas", domain: "social" },
    { id: "T19", text: "How often do you feel envious of what others have or have achieved?", category: "tamas", domain: "social" },
    { id: "T26", text: "I often neglect my responsibilities towards my friends", category: "tamas", domain: "social" },
    { id: "T27", text: "How often do you act aggressively or violently towards others?", category: "tamas", domain: "social" },


    // --- SECTION 3: LIFESTYLE & HABITS (Food, Money, Technology) ---
    { id: "S1", text: "When given a choice at a buffet, how often do you naturally gravitate towards fresh fruits and salads over heavy or spicy dishes?", category: "sattva", domain: "lifestyle" },
    { id: "S5", text: "If a cashier gives you extra money by mistake, how likely are you to immediately point out the error and return it?", category: "sattva", domain: "lifestyle" },
    { id: "R6", text: "To what extent do you live your life with the assumption that this physical existence is the only reality that matters?", category: "rajas", domain: "lifestyle" },
    { id: "R8", text: "How much do you crave spicy, salty, or very rich foods (like fried snacks or heavy desserts) compared to plain, simple meals?", category: "rajas", domain: "lifestyle" },
    { id: "R9", text: "If you lost your phone or favorite watch today, how strongly would it affect your mood and sense of self-worth for the next week?", category: "rajas", domain: "lifestyle" },
    { id: "R10", text: "On a free evening, how often do you choose loud social outings (parties, clubs) over quiet, solitary activities?", category: "rajas", domain: "lifestyle" },
    { id: "R11", text: "How often do you spend more than an hour a day thinking about or pursuing romantic/sexual gratification?", category: "rajas", domain: "lifestyle" },
    { id: "R12", text: "When looking at a buffet or a sale, do you often take more than you actually need, just because it's available?", category: "rajas", domain: "lifestyle" },
    { id: "R14", text: "After buying something you really wanted, how quickly do you start wanting a better version of it?", category: "rajas", domain: "lifestyle" },
    { id: "R15", text: "How often do you feel you could be genuinely happy living in a simple house without luxury items?", category: "rajas", reverse: true, domain: "lifestyle" },
    { id: "R16", text: "How frequently do you prioritize physical enjoyment (like food, comfort, or sex) over your other responsibilities?", category: "rajas", domain: "lifestyle" },
    { id: "T2", text: "How often do you act on impulse without stopping to think about the consequences?", category: "tamas", domain: "lifestyle" },
    { id: "T5", text: "How often do you struggle to get out of bed because the day ahead feels pointless or too heavy?", category: "tamas", domain: "lifestyle" },
    { id: "T21", text: "If you could get away with not paying a bus fare or sneaking into a movie, would you do it?", category: "tamas", domain: "lifestyle" },
    { id: "T22", text: "If there is a box of cookies in front of you and you decided not to eat one, how often do you end up giving in anyway?", category: "tamas", domain: "lifestyle" },
    { id: "T23", text: "How often do you find yourself wishing you could escape to a quiet village rather than living in the busy city?", category: "tamas", domain: "lifestyle" },
    { id: "T24", text: "How often do you feel controlled by a physical or psychological habit/addiction that you can't break?", category: "tamas", domain: "lifestyle" },


    // --- SECTION 4: INNER SELF (Thoughts, Ethics, Anxiety) ---
    { id: "S2", text: "When you look at an animal or another person, to what extent do you feel a deep, underlying connection or shared 'life force' with them?", category: "sattva", domain: "inner" },
    { id: "S7", text: "When facing a difficult decision where you could gain personally by bending the rules, how often do you stop to ask yourself 'Is this the right thing to do?'", category: "sattva", domain: "inner" },
    { id: "S8", text: "Imagine you made a mistake at work/school that no one else noticed. How likely are you to admit it voluntarily?", category: "sattva", domain: "inner" },
    { id: "S10", text: "Think about a time when you had nothing to do and no entertainment. How comfortable/happy were you just 'being' with yourself?", category: "sattva", domain: "inner" },
    { id: "S13", text: "Before taking action, how often do you consult higher ethical or moral principles?", category: "sattva", domain: "inner" },
    { id: "S14", text: "How often do you feel that 'self-realization' or 'spiritual growth' is irrelevant to your real-life goals?", category: "sattva", reverse: true, domain: "inner" },
    { id: "T3", text: "On a typical day, what percentage of the time do you feel a general sense of 'blah' or dissatisfaction for no specific reason?", category: "tamas", domain: "inner" },
    { id: "T10", text: "How often do you become greatly upset or distressed when things don't go according to plan?", category: "tamas", domain: "inner" },
    { id: "T13", text: "How often do you feel fearful or afraid, even when there is no immediate danger?", category: "tamas", domain: "inner" },
    { id: "T14", text: "Do your moods swing wildly during the day (e.g., fine one minute, crying/angry the next)?", category: "tamas", domain: "inner" },
    { id: "T16", text: "How often do you feel 'down in the dumps' or 'low energy' even when nothing bad has happened?", category: "tamas", domain: "inner" },
    { id: "T17", text: "Do you often 'forget' or avoid doing chores/errands that your family asked you to do?", category: "tamas", domain: "inner" },
    { id: "T25", text: "I often feel mentally unbalanced or chaotic inside", category: "tamas", domain: "inner" }
];

export const bigFiveItems = [
    // Reflective Big Five Items (adapted from BFI-10, Rammstedt & John, 2007)
    // Rewritten as behavioral statements for deeper self-reflection
    { id: "BFI1", text: "Is talkative", trait: "Extraversion", reverse: false },
    { id: "BFI2", text: "Tends to find fault with others", trait: "Agreeableness", reverse: true },
    { id: "BFI3", text: "Does a thorough job", trait: "Conscientiousness", reverse: false },
    { id: "BFI4", text: "Is depressed, blue", trait: "Neuroticism", reverse: false },
    { id: "BFI5", text: "Is original, comes up with new ideas", trait: "Openness", reverse: false },
    { id: "BFI6", text: "Is reserved", trait: "Extraversion", reverse: true },
    { id: "BFI7", text: "Is helpful and unselfish with others", trait: "Agreeableness", reverse: false },
    { id: "BFI8", text: "Can be somewhat careless", trait: "Conscientiousness", reverse: true },
    { id: "BFI9", text: "Is relaxed, handles stress well", trait: "Neuroticism", reverse: true },
    { id: "BFI10", text: "Is curious about many different things", trait: "Openness", reverse: false },
    { id: "BFI11", text: "Is full of energy", trait: "Extraversion", reverse: false },
    { id: "BFI12", text: "Starts quarrels with others", trait: "Agreeableness", reverse: true },
    { id: "BFI13", text: "Is a reliable worker", trait: "Conscientiousness", reverse: false },
    { id: "BFI14", text: "Can be tense", trait: "Neuroticism", reverse: false },
    { id: "BFI15", text: "Is ingenious, a deep thinker", trait: "Openness", reverse: false },
    { id: "BFI16", text: "Generates a lot of enthusiasm", trait: "Extraversion", reverse: false },
    { id: "BFI17", text: "Has a forgiving nature", trait: "Agreeableness", reverse: false },
    { id: "BFI18", text: "Tends to be disorganized", trait: "Conscientiousness", reverse: true },
    { id: "BFI19", text: "Worries a lot", trait: "Neuroticism", reverse: false },
    { id: "BFI20", text: "Has an active imagination", trait: "Openness", reverse: false },
    { id: "BFI21", text: "Tends to be quiet", trait: "Extraversion", reverse: true },
    { id: "BFI22", text: "Is generally trusting", trait: "Agreeableness", reverse: false },
    { id: "BFI23", text: "Tends to be lazy", trait: "Conscientiousness", reverse: true },
    { id: "BFI24", text: "Is emotionally stable, not easily upset", trait: "Neuroticism", reverse: true },
    { id: "BFI25", text: "Is inventive", trait: "Openness", reverse: false },
    { id: "BFI26", text: "Has an assertive personality", trait: "Extraversion", reverse: false },
    { id: "BFI27", text: "Can be cold and aloof", trait: "Agreeableness", reverse: true },
    { id: "BFI28", text: "Perseveres until the task is finished", trait: "Conscientiousness", reverse: false },
    { id: "BFI29", text: "Can be moody", trait: "Neuroticism", reverse: false },
    { id: "BFI30", text: "Values artistic, aesthetic experiences", trait: "Openness", reverse: false },
    { id: "BFI31", text: "Is sometimes shy, inhibited", trait: "Extraversion", reverse: true },
    { id: "BFI32", text: "Is considerate and kind to almost everyone", trait: "Agreeableness", reverse: false },
    { id: "BFI33", text: "Does things efficiently", trait: "Conscientiousness", reverse: false },
    { id: "BFI34", text: "Remains calm in tense situations", trait: "Neuroticism", reverse: true },
    { id: "BFI35", text: "Prefers work that is routine", trait: "Openness", reverse: true },
    { id: "BFI36", text: "Is outgoing, sociable", trait: "Extraversion", reverse: false },
    { id: "BFI37", text: "Is sometimes rude to others", trait: "Agreeableness", reverse: true },
    { id: "BFI38", text: "Makes plans and follows through with them", trait: "Conscientiousness", reverse: false },
    { id: "BFI39", text: "Gets nervous easily", trait: "Neuroticism", reverse: false },
    { id: "BFI40", text: "Likes to reflect, play with ideas", trait: "Openness", reverse: false },
    { id: "BFI41", text: "Has few artistic interests", trait: "Openness", reverse: true },
    { id: "BFI42", text: "Likes to cooperate with others", trait: "Agreeableness", reverse: false },
    { id: "BFI43", text: "Is easily distracted", trait: "Conscientiousness", reverse: true },
    { id: "BFI44", text: "Is sophisticated in art, music, or literature", trait: "Openness", reverse: false }
];
